/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MechanicsRouteImport } from './routes/mechanics'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRmRoomIdRouteRouteImport } from './routes/app/rm.$roomId/route'
import { Route as AppRmCreateIndexRouteImport } from './routes/app/rm.create/index'
import { Route as AppRmRoomIdIndexRouteImport } from './routes/app/rm.$roomId/index'
import { Route as ApiRoomRoomIdWsRouteImport } from './routes/api/room/$roomId/ws'

const MechanicsRoute = MechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRmRoomIdRouteRoute = AppRmRoomIdRouteRouteImport.update({
  id: '/rm/$roomId',
  path: '/rm/$roomId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRmCreateIndexRoute = AppRmCreateIndexRouteImport.update({
  id: '/rm/create/',
  path: '/rm/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRmRoomIdIndexRoute = AppRmRoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRmRoomIdRouteRoute,
} as any)
const ApiRoomRoomIdWsRoute = ApiRoomRoomIdWsRouteImport.update({
  id: '/api/room/$roomId/ws',
  path: '/api/room/$roomId/ws',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/mechanics': typeof MechanicsRoute
  '/app/': typeof AppIndexRoute
  '/app/rm/$roomId': typeof AppRmRoomIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/room/$roomId/ws': typeof ApiRoomRoomIdWsRoute
  '/app/rm/$roomId/': typeof AppRmRoomIdIndexRoute
  '/app/rm/create/': typeof AppRmCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mechanics': typeof MechanicsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/room/$roomId/ws': typeof ApiRoomRoomIdWsRoute
  '/app/rm/$roomId': typeof AppRmRoomIdIndexRoute
  '/app/rm/create': typeof AppRmCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/mechanics': typeof MechanicsRoute
  '/app/': typeof AppIndexRoute
  '/app/rm/$roomId': typeof AppRmRoomIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/room/$roomId/ws': typeof ApiRoomRoomIdWsRoute
  '/app/rm/$roomId/': typeof AppRmRoomIdIndexRoute
  '/app/rm/create/': typeof AppRmCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/mechanics'
    | '/app/'
    | '/app/rm/$roomId'
    | '/api/auth/$'
    | '/api/room/$roomId/ws'
    | '/app/rm/$roomId/'
    | '/app/rm/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mechanics'
    | '/app'
    | '/api/auth/$'
    | '/api/room/$roomId/ws'
    | '/app/rm/$roomId'
    | '/app/rm/create'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/mechanics'
    | '/app/'
    | '/app/rm/$roomId'
    | '/api/auth/$'
    | '/api/room/$roomId/ws'
    | '/app/rm/$roomId/'
    | '/app/rm/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MechanicsRoute: typeof MechanicsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRoomRoomIdWsRoute: typeof ApiRoomRoomIdWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mechanics': {
      id: '/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof MechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rm/$roomId': {
      id: '/app/rm/$roomId'
      path: '/rm/$roomId'
      fullPath: '/app/rm/$roomId'
      preLoaderRoute: typeof AppRmRoomIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rm/create/': {
      id: '/app/rm/create/'
      path: '/rm/create'
      fullPath: '/app/rm/create/'
      preLoaderRoute: typeof AppRmCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rm/$roomId/': {
      id: '/app/rm/$roomId/'
      path: '/'
      fullPath: '/app/rm/$roomId/'
      preLoaderRoute: typeof AppRmRoomIdIndexRouteImport
      parentRoute: typeof AppRmRoomIdRouteRoute
    }
    '/api/room/$roomId/ws': {
      id: '/api/room/$roomId/ws'
      path: '/api/room/$roomId/ws'
      fullPath: '/api/room/$roomId/ws'
      preLoaderRoute: typeof ApiRoomRoomIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRmRoomIdRouteRouteChildren {
  AppRmRoomIdIndexRoute: typeof AppRmRoomIdIndexRoute
}

const AppRmRoomIdRouteRouteChildren: AppRmRoomIdRouteRouteChildren = {
  AppRmRoomIdIndexRoute: AppRmRoomIdIndexRoute,
}

const AppRmRoomIdRouteRouteWithChildren =
  AppRmRoomIdRouteRoute._addFileChildren(AppRmRoomIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppRmRoomIdRouteRoute: typeof AppRmRoomIdRouteRouteWithChildren
  AppRmCreateIndexRoute: typeof AppRmCreateIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppRmRoomIdRouteRoute: AppRmRoomIdRouteRouteWithChildren,
  AppRmCreateIndexRoute: AppRmCreateIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  MechanicsRoute: MechanicsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRoomRoomIdWsRoute: ApiRoomRoomIdWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
